# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576fd49aa3cbc82661d26a35b94b83be8b256effd1f49a5eaa33d194f8e0bd09717ecb02cfbb4493f3c687711f8e634f9195d58aeacd3556e802c3155812fafe

test:
  secret_key_base: 7511c9a54fc472eb1f30800dbcda74e128e89f4965169cb18f0f2203072a550d9ed3b59386c44160953c2573d61aa5a69b5142ad1addb4fbb25a92f0030bc9bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
